### ISSUE TITLE
Format Syslog

### ISSUE THREAD

**Issue by patton1907** [johestephan/TwitterMonitor#1]
Change syslog format To:
 logmessage = '''TwitterBot|FoundDomain: %s|NumberofFindings: %s|SourceURL: %s |SourceTwitterID: %s)\n''' % (word, len(Findings), d1,d3)
To make it easier ingested by software

**Comment by johestephan** [comment]
Okay, so the log entries would look like this

> 
> Sep 14 10:42:07 johest-ThinkPad-T410 tr.py: TwitterBot|FoundDomain: yahoo.com|NumberofFindings: 1|SourceURL: https://t.co/cn4tBz3b6o |SourceTwitterID: 908243836983562240)
> Sep 14 10:42:11 johest-ThinkPad-T410 tr.py: TwitterBot|FoundDomain: yahoo.com|NumberofFindings: 15|SourceURL: https://t.co/PnEETTrKGJ |SourceTwitterID: 908215576211968001)
> Sep 14 10:42:13 johest-ThinkPad-T410 tr.py: TwitterBot|FoundDomain: yahoo.com|NumberofFindings: 15|SourceURL: https://t.co/tpNBzDPNdf |SourceTwitterID: 908214957384372224)
> Sep 14 10:42:17 johest-ThinkPad-T410 tr.py: TwitterBot|FoundDomain: yahoo.com|NumberofFindings: 361|SourceURL: https://t.co/URXeGVwMWs |SourceTwitterID: 908203480741019648)
> Sep 14 10:42:19 johest-ThinkPad-T410 tr.py: TwitterBot|FoundDomain: yahoo.com|NumberofFindings: 189|SourceURL: https://t.co/VE9U3Y7wBJ |SourceTwitterID: 908194177992806400)
> Sep 14 10:42:21 johest-ThinkPad-T410 tr.py: TwitterBot|FoundDomain: yahoo.com|NumberofFindings: 44|SourceURL: https://t.co/xzOyiZ8zyt |SourceTwitterID: 908184867401342977)

**Comment by patton1907** [comment]
logmessage = '''TwitterBot|FoundDomain: %s|NumberofFindings: %s|SourceURL: %s |SourceTwitterID: %s\n''' % (word, len(Findings), d1,d3)

This would be the format we would need

**Comment by johestephan** [comment]
okay, seems to fit.
the beginning of the line is by syslog and cant be adjusted (easily)
